[package]
name = "kiln-cli"
version.workspace = true
description = "CLI for Kiln container image builder"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kiln"
path = "src/main.rs"

[dependencies]
kiln-core = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
